In [3]:
import torch
print(torch.cuda.is_available())
print(torch.__version__)

True
2.10.0+cu126


In [38]:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1, 2])
tensor2d = torch.tensor([[1,2],[3,4]])
tensor3d = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor3dfloat = torch.tensor([[[1.0,2],[3,4]],[[5,6],[7,8]]])
transformed_float = tensor3d.to(torch.float64)

In [39]:
print(tensor0d)
print(tensor1d)
print(tensor2d)
print(tensor3d)
print(tensor3dfloat)
print(transformed_float)

tensor(1)
tensor([1, 2])
tensor([[1, 2],
        [3, 4]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]], dtype=torch.float64)


In [40]:
print(tensor0d.dtype)
print(tensor1d.dtype)
print(tensor2d.dtype)
print(tensor3d.dtype)
print(tensor3dfloat.dtype)
print(transformed_float.dtype)

torch.int64
torch.int64
torch.int64
torch.int64
torch.float32
torch.float64


In [41]:
print(transformed_float.shape)
reshaped = tensor3d.T.reshape(2,4)# Transpose on 3d is really weird.
print(reshaped)
print(tensor3d.T)

torch.Size([2, 2, 2])
tensor([[1, 5, 3, 7],
        [2, 6, 4, 8]])
tensor([[[1, 5],
         [3, 7]],

        [[2, 6],
         [4, 8]]])


In [45]:
tensor1d @ tensor2d # This is also a matrix multiplication.

tensor([ 7, 10])